import type {ValuationData} from "./types";

export const valuationData: ValuationData = {
    stocks: [
        {
            symbol: "AAPL",
            name: "蘋果",
            market: "US",
            valuationLow: 189.52,
            valuationHigh: 288.4,
        },
        {
            symbol: "AMZN",
            name: "亞馬遜",
            market: "US",
            valuationLow: 218.88,
            valuationHigh: 304.0,
        },
        {
            symbol: "AVGO",
            name: "博通",
            market: "US",
            valuationLow: 250.0,
            valuationHigh: 400.0,
        },
        {
            symbol: "COIN",
            name: "Coinbase",
            market: "US",
            valuationLow: 172.8,
            valuationHigh: 345.6,
        },
        {
            symbol: "CRM",
            name: "Salesforce",
            market: "US",
            valuationLow: 215,
            valuationHigh: 343.9,
        },
        {
            symbol: "ETN",
            name: "Eastman Chemical",
            market: "US",
            valuationLow: 267.2,
            valuationHigh: 427.6,
        },
        {
            symbol: "GOOG",
            name: "谷歌",
            market: "US",
            valuationLow: 239.2,
            valuationHigh: 358.8,
        },
        {
            symbol: "HON",
            name: "霍尼韋爾",
            market: "US",
            valuationLow: 177.1,
            valuationHigh: 260.5,
        },
        {
            symbol: "HOOD",
            name: "Robinhood",
            market: "US",
            valuationLow: 78.75,
            valuationHigh: 141.75,
        },
        {
            symbol: "META",
            name: "Meta",
            market: "US",
            valuationLow: 534.7,
            valuationHigh: 802.06,
        },
        {
            symbol: "MSFT",
            name: "微軟",
            market: "US",
            valuationLow: 503.75,
            valuationHigh: 705.25,
        },
        {
            symbol: "NVDA",
            name: "英偉達",
            market: "US",
            valuationLow: 193.25,
            valuationHigh: 309.2,
        },
        {
            symbol: "TSM",
            name: "台積電",
            market: "US",
            valuationLow: 254.4,
            valuationHigh: 381.6,
        },
        {
            symbol: "0388.HK",
            name: "港交所",
            market: "HK",
            valuationLow: 334,
            valuationHigh: 536,
        },

        {
            symbol: "0700.HK",
            name: "騰訊",
            market: "HK",
            valuationLow: 525,
            valuationHigh: 875,
        },
        {
            symbol: "2899.HK",
            name: "紫金礦業",
            market: "HK",
            valuationLow: 36.14,
            valuationHigh: 50.04,
        },
        {
            symbol: "0883.HK",
            name: "中國海洋石油",
            market: "HK",
            valuationLow: 15.38,
            valuationHigh: 24.65,
        },
        {
            symbol: "1088.HK",
            name: "中國神華",
            market: "HK",
            valuationLow: 28,
            valuationHigh: 44,
        },
        {
            symbol: "0358.HK",
            name: "江西銅業",
            market: "HK",
            valuationLow: 13,
            valuationHigh: 26,
        },
        {
            symbol: "2333.HK",
            name: "長城汽車",
            market: "HK",
            valuationLow: 11.55,
            valuationHigh: 26.6,
        },
        {
            symbol: "9868.HK",
            name: "小鵬汽車",
            market: "HK",
            valuationLow: 67.4,
            valuationHigh: 101,
        },

        {
            symbol: "0175.HK",
            name: "吉利汽車",
            market: "HK",
            valuationLow: 13.3,
            valuationHigh: 26.6,
        },
    ],
};
