import type {ValuationData} from "@/types";

export const valuationData: ValuationData = {
    stocks: [
        {
            symbol: "AAPL",
            valuationLow: 189.52,
            valuationHigh: 288.4,
            // EPS: 8.24,
            // Lowest P/E: 23,
            // Highest P/E: 35,
        },
        {
            symbol: "AMZN",
            valuationLow: 218.88,
            valuationHigh: 304.0,
            // OCF: 12.16,
            // Lowest P/OCF: 18,
            // Highest P/OCF: 25,
        },
        {
            symbol: "AVGO",
            valuationLow: 250.0,
            valuationHigh: 400.0,
            // EPS: 10,
            // Lowest P/E: 25,
            // Highest P/E: 40,
        },
        {
            symbol: "COIN",
            valuationLow: 172.8,
            valuationHigh: 345.6,
            // SPS: 28.8,
            // Lowest P/S: 6,
            // Highest P/S: 12,
        },
        {
            symbol: "CRM",
            valuationLow: 215,
            valuationHigh: 343.9,
            // SPS: 13.19,
            // Lowest P/S: 5,
            // Highest P/S: 8,
        },
        {
            symbol: "ETN",

            valuationLow: 267.2,
            valuationHigh: 427.6,
            // EPS: 13.36,
            // Lowest P/E: 20,
            // Highest P/E: 32,
        },
        {
            symbol: "GOOG",
            valuationLow: 239.2,
            valuationHigh: 358.8,
            // EPS: 11.96,
            // Lowest P/E: 20,
            // Highest P/E: 30,
        },
        {
            symbol: "HON",
            valuationLow: 177.1,
            valuationHigh: 260.5,
            // EPS: 10.42,
            // Lowest P/E: 17,
            // Highest P/E: 25,
        },
        {
            symbol: "HOOD",
            valuationLow: 78.75,
            valuationHigh: 141.75,
            // EPS: 3.15,
            // Lowest P/E: 25,
            // Highest P/E: 45,
        },
        {
            symbol: "META",
            valuationLow: 534.7,
            valuationHigh: 802.06,
            // EPS: 26.74,
            // Lowest P/E: 20,
            // Highest P/E: 30,
        },
        {
            symbol: "MSFT",
            valuationLow: 503.75,
            valuationHigh: 705.25,
            // EPS: 20.15,
            // Lowest P/E: 25,
            // Highest P/E: 35,
        },
        {
            symbol: "NVDA",
            valuationLow: 193.25,
            valuationHigh: 309.2,
            // EPS: 7.73,
            // Lowest P/E: 25,
            // Highest P/E: 40,
        },
        {
            symbol: "TSM",
            valuationLow: 254.4,
            valuationHigh: 381.6,
            // EPS: 12.72,
            // Lowest P/E: 20,
            // Highest P/E: 30,
        },
        {
            symbol: "0388.HK",
            valuationLow: 334,
            valuationHigh: 536,
            // EPS: 13.4,
            // Lowest P/E: 25,
            // Highest P/E: 40,
        },

        {
            symbol: "0700.HK",
            valuationLow: 525,
            valuationHigh: 875,
            // EPS: 35.33,
            // Lowest P/E: 15,
            // Highest P/E: 25,
        },
        {
            symbol: "2899.HK",
            valuationLow: 36.14,
            valuationHigh: 50.04,
            // EPS: 2.78,
            // Lowest P/E: 13,
            // Highest P/E: 20,
        },
        {
            symbol: "0883.HK",
            valuationLow: 15.38,
            valuationHigh: 24.65,
            // Dividend: 1.23,
            // Lowest Dividend Yield: 0.05,
            // Highest Dividend Yield: 0.08,
        },
        {
            symbol: "1088.HK",
            valuationLow: 28,
            valuationHigh: 44,
            // Dividend: 2.2,
            // Lowest Dividend Yield: 0.05,
            // Highest Dividend Yield: 0.08,
        },
        {
            symbol: "0358.HK",
            valuationLow: 13,
            valuationHigh: 26,
            // NAV: 26,
            // Lowest P/B: 0.5,
            // Highest P/B: 1.0,
        },
        {
            symbol: "2333.HK",
            valuationLow: 11.55,
            valuationHigh: 26.6,
            // EPS: 1.65,
            // Lowest P/E: 7,
            // Highest P/E: 14,
        },
        {
            symbol: "9868.HK",
            valuationLow: 67.4,
            valuationHigh: 101,
            // SPS: 67.4,
            // Lowest P/S: 1,
            // Highest P/S: 1.5,
        },

        {
            symbol: "0175.HK",
            valuationLow: 13.3,
            valuationHigh: 26.6,
            // EPS: 1.9,
            // Lowest P/E: 7,
            // Highest P/E: 14,
        },
        {
            symbol: "3750.HK",
            valuationLow: 408.6,
            valuationHigh: 635.6,
            // EPS: 22.7,
            // Lowest P/E: 18,
            // Highest P/E: 28,
        },
    ],
};
